# Generated by Django 4.2.11 on 2024-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField()),
                ('labels', models.IntegerField()),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
    ]
