# Generated by Django 4.2.11 on 2024-05-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0002_featuredata'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredata',
            name='cluster_labels',
            field=models.IntegerField(default=0),
        ),
    ]
