# Generated by Django 4.2.11 on 2024-05-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0003_featuredata_cluster_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredata',
            name='cluster_labels',
            field=models.IntegerField(default=1),
        ),
    ]
