# Generated by Django 4.2.11 on 2024-05-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0004_alter_featuredata_cluster_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField()),
                ('labels', models.JSONField()),
                ('image_path', models.CharField(max_length=255)),
                ('cluster_labels', models.IntegerField(default=1)),
            ],
        ),
    ]
